### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by lolpoe** [L0SER8228/discord-lavalink-music-bot#14]
SyntaxError: Invalid regular expression: /^(<@!?906508685977727026>|!\s*/: Unterminated group
    at new RegExp (<anonymous>)
    at execute (/root/discord-lavalink-music-bot/src/events/message/messageCreate.js:27:22)
    at Client.emit (node:events:394:28)
    at MessageCreateAction.handle (/root/discord-lavalink-music-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:25:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/discord-lavalink-music-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/discord-lavalink-music-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:350:31)
    at WebSocketShard.onPacket (/root/discord-lavalink-music-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (/root/discord-lavalink-music-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
    at WebSocket.onMessage (/root/discord-lavalink-music-bot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:394:28)

**Comment by L0SER8228** [comment]
I've updated, hope it'll close this issue
